services:
  helloworld:
    image: traefik/whoami
    hostname: helloworld
    command: 
      - --verbose
    
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - helloworld
    ports:
      - "4000:4000"
  
networks:
  default:
    driver: bridge
    name: helloworld
